name: Run Shopify Script

on:
  schedule:
    - cron:  '0 11,13,15,17,19,21 * * *' # Run every 2 hrs during the work day, EST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: env
    steps:
    - uses: actions/checkout@v4 

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Updated to Node.js 20

    - name: Install dependencies
      run: npm install

    - name: List environment variables
      run: env

    - name: Run the script
      env:
        SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
        SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        SHOPIFY_API_SECRET_KEY: ${{ secrets.SHOPIFY_API_SECRET_KEY }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        SHOPIFY_API_SCOPES: ${{ secrets.SHOPIFY_API_SCOPES }}
        SHOPIFY_LOCATION_ID: ${{ secrets.SHOPIFY_LOCATION_ID }}
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: node index.js
