name: rsr/shopify sync

on:
  workflow_dispatch:
  schedule:
    - cron:  '10 12,14,16,18,20,22,0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4 

    - name: set up node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: install dependencies
      run: npm ci

    - name: list env vars
      run: env

    - name: run script
      env:
        SHOPIFY_STORE_NAME: ${{ secrets.SHOPIFY_STORE_NAME }}
        SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        SHOPIFY_API_SECRET_KEY: ${{ secrets.SHOPIFY_API_SECRET_KEY }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        SHOPIFY_API_SCOPES: ${{ secrets.SHOPIFY_API_SCOPES }}
        SHOPIFY_LOCATION_ID: ${{ secrets.SHOPIFY_LOCATION_ID }}
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: node app.js
